### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by GO-Loc-GO** [Coolzyh/Globecom2020-ResourceAllocationGNN#4]
Hi Coozyh, I'm very interested in your nice hard work done here and I'm trying to run your code. However, upon running the code I met the following problem which I have no clue in solving and I would really appreciate your help.

So I installed the packages according to the specification in the README file. Here is the list of dependencies:
(1) Keras 2.2.4
(2) TensorFlow 1.14.0

And my system specifications are:
(1) GPU: NVIDIA 4060 on PC
(2) CUDA: 12.0
(3) cuDNN: 8.0 I suppose.

When trying to run RL_Train_Main.py, I'm having the module not found error for '_pywrap_tensorflow_internal'. Specifically :
{Using TensorFlow backend.
Traceback (most recent call last):
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "d:\Anaconda3\envs\GNN\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Active_Files\lectures\PhD 1st Year\图机器学习\报告\Globecom2020-ResourceAllocationGNN-main\BS_brain.py", line 6, in <module>
    import keras
  File "d:\Anaconda3\envs\GNN\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "d:\Anaconda3\envs\GNN\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "d:\Anaconda3\envs\GNN\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "d:\Anaconda3\envs\GNN\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "d:\Anaconda3\envs\GNN\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "d:\Anaconda3\envs\GNN\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "d:\Anaconda3\envs\GNN\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.}

I'm not sure what's causing this though I suspect it may because the CUDA or cuDNN version are incompatible with tensorflow. Could u  pls offer a solution to this?

**Comment by RedLotusGG** [comment]
Have you solved your problem?

**Comment by GO-Loc-GO** [comment]
Unfortunately, no and I gave up running the code, it’s probably too old to run properly.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Baochen Xu ***@***.***>
发送时间: Saturday, September 14, 2024 9:09:32 AM
收件人: Coolzyh/Globecom2020-ResourceAllocationGNN ***@***.***>
抄送: SeanZu ***@***.***>; Author ***@***.***>
主题: Re: [Coolzyh/Globecom2020-ResourceAllocationGNN] Unable to run the code (Issue #4)


Have you solved your problem?

―

**Comment by Coolzyh** [comment]
Yes, the TensorFlow version is too old and cannot supported by your CUDA version
